<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="Cart.aspx.cs" Inherits="Cart" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
    <!-- <p>
        <strong>Products:</strong><asp:Label ID="lbl_prods" runat="server"></asp:Label>
    </p>
    <p>
        <strong>Quantities:</strong><asp:Label ID="lbl_qtys" runat="server"></asp:Label>
    </p>
    <p>
        <strong>--------------------------------------------------- THIS LINE AND ABOVE IS TEMPORARY ----------------------------------</strong></p> -->
    <p>
        &nbsp;</p>
    <p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" CellPadding="4" ForeColor="Black" GridLines="Horizontal" Height="319px" OnRowDeleting="GridView1_RowDeleting" ShowFooter="True" Width="1061px" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px">
            <Columns>
                <asp:BoundField DataField="ROWNUM" HeaderText="Item Number" />
                <asp:BoundField DataField="product_id" HeaderText="Product ID" />
                <asp:BoundField DataField="productname" HeaderText="Product Name" />
                <asp:BoundField DataField="saleprice" HeaderText="Price" />
                <asp:BoundField DataField="QTY_ORDER" HeaderText="Quantity" />
                <asp:BoundField DataField="LineTotal" HeaderText="Line Total" />
            </Columns>
            <FooterStyle BackColor="#333333" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>
    </p>
    <p>
    </p>
    <p>
        <asp:Button ID="btn_checkout" runat="server" OnClick="Btn_checkout_Click" Text="Checkout" />
    </p>
    <p>
    </p>
    <p>
    </p>
</asp:Content>

